[package]
name = "arbitro-raft"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
async-trait = "0.1"
tracing = "0.1"
zerocopy = { version = "0.8", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["async_tokio"] }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-uring = "0.5"

[[bench]]
name = "inline_bench"
harness = false

[[bench]]
name = "alloc_bench"
harness = false

[[bench]]
name = "tcp_full_bench"
harness = false

[[bench]]
name = "async_tcp_bench"
harness = false

[[bench]]
name = "memory_e2e_bench"
harness = false
